org: torracodes
app: slsgbackend
service: slsbackend

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  logRetentionInDays: 7
  environment:
    TABLE_NAME: ${self:service}-grants-${self:provider.stage} #TODO: slsbackend-x-dev/staging/prod need to add options
    USER_POOL_ID: !Ref CognitoUserPool
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: !GetAtt GrantsTable.Arn

custom:
  corsSettings:
    origin: http://localhost:5173,https://notsurewhatyouareyet.com
    headers:
      - Content-Type
      - Authorization
    allowCredentials: true

functions:
  getGrant:
    handler: src/features/grants/lambdas/getGrant.handler
    events:
      - http:
          path: /grants/{id}
          method: get
          cors: ${self:custom.corsSettings}
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  getGrantsByUserId:
    handler: src/features/grants/lambdas/getGrantsByUserId.handler
    events:
      - http:
          path: /users/{userId}/grants
          method: get
          cors: ${self:custom.corsSettings}
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  createGrant:
    handler: src/features/grants/lambdas/createGrant.handler
    events:
      - http:
          path: /grants
          method: post
          cors: ${self:custom.corsSettings}
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  updateGrant:
    handler: src/features/grants/lambdas/updateGrant.handler
    events:
      - http:
          path: /grants/{id}
          method: put
          cors: ${self:custom.corsSettings}
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  deleteGrant:
    handler: src/features/grants/lambdas/deleteGrant.handler
    events:
      - http:
          path: /grants/{id}
          method: delete
          cors: ${self:custom.corsSettings}
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:service}-api-${self:provider.stage}
    GrantsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: userSubId
            AttributeType: S
          - AttributeName: grantId
            AttributeType: S
        # Ideally fetch all items a user has using PK without full table scan
        KeySchema:
          - AttributeName: userSubId
            KeyType: HASH
          - AttributeName: grantId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:service}-user-pool-${self:provider.stage}
        AutoVerifiedAttributes: [email]

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:service}-client-${self:provider.stage}
        GenerateSecret: false
        UserPoolId: !Ref CognitoUserPool

    ApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: cognito-authorizer
        Type: COGNITO_USER_POOLS
        RestApiId:
          Ref: ApiGatewayRestApi
        IdentitySource: method.request.header.Authorization
        ProviderARNs:
          - !GetAtt CognitoUserPool.Arn
